name: Playwright Tests
on:
  push:
    branches: [ master, "**"]
  pull_request:
    branches: [ master, "**"]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        check-latest: true
    - name: Install dependencies
      working-directory: ./my_website
      run: npm install
    - name: Install Playwright Browsers
      working-directory: ./my_website
      run: npx playwright install --with-deps
    - name: Build Next Server
      working-directory: ./my_website
      run: npm run build
    - name: Run Playwright tests
      working-directory: ./my_website
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./my_website/playwright-report/
        retention-days: 30
